version: '3.8'
services:
  postgres_manutencao:
    container_name: postgres_manutencao
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: db_manutencao
      POSTGRES_USER: manutencao_user
      POSTGRES_PASSWORD: manutencao_pass
    volumes:
      - postgres_manutencao_data:/var/lib/postgresql/postgres_manutencao

  pgadmin_manutencao:
    container_name: pgadmin_manutencao
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8172:80"
    depends_on:
      - postgres_manutencao

  app_manutencao:
    container_name: app_manutencao
    image: manutencao-aeronave:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres_manutencao

volumes:
  postgres_manutencao_data:
